<?php

namespace app\v1\wechat\controller;

class message extends info
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function send()
    {

    }
}