<?php

namespace app\v1\wechat\controller;

use app\v1\image\controller\create;
use app\v1\wechat\model\WechatModel;
use Wechat\Miniprogram;

class offiaccount extends create
{

    public mixed $access_token;
    public string $appid;
    public string $appsecret;
    public string $path_prefix = './upload/';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $wechat = WechatModel::where('project', $this->token)->find();
        if (!$wechat) {
            \Ret::Fail(404, null, '未找到项目');
        }
        $this->appid = $wechat['appid'];
        $this->appsecret = $wechat['appsecret'];
        $this->access_token = $wechat['access_token'];

        $expire_after = strtotime($wechat['expire_after']);
        if ($expire_after < time() || empty($wechat['access_token'])) {
            $data = Miniprogram::getAccessToken($this->appid, $this->appsecret);
            if ($data->isSuccess()) {
                $this->access_token = $data->access_token;
                WechatModel::where('project', $this->token)->data(
                    [
                        'access_token' => $data->access_token,
                        'expire_after' => date('Y-m-d H:i:s', $data->expires_in + time() - 600)
                    ]
                )->update();
            } else {
                echo $data->error();
                exit();
            }
        }
    }
}