<?php

namespace app\v1\wechat\controller;

use app\v1\wechat\model\WechatModel;
use think\Request;

class ticket extends wxa
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $ticket_expire_after = strtotime($this->wechat['ticket_expire_after']);
        if ($ticket_expire_after < time() || empty($this->access_token)) {
            $this->getticket();
        }
    }

    public function getticket(Request $request)
    {

        $ticket = \Wechat\Ticket::getTicket($this->access_token);
        if ($ticket->isSuccess()) {
            WechatModel::where("project", $this->token)->update([
                "ticket" => $ticket->ticket,
                'ticket_expire_after' => $ticket->expires_in + time() - 600
            ]);
            \Ret::Success(0, $ticket->isSuccess());
        } else {
            \Ret::Fail(300, $ticket->response, $ticket->error());
        }
    }

    public function signature(Request $request)
    {
        $noncestr = input("noncestr");
        $jsapi_ticket = input("jsapi_ticket");
        $timestamp = input('timestamp');
        $url = input('url');
        $post = [
            'noncestr' => $noncestr,
            'jsapi_ticket' => $jsapi_ticket,
            'timestamp' => $timestamp,
            'url' => $url,
        ];
        ksort($post);
        $str = http_build_query($post);
        \Ret::Success(0, sha1($str));
    }

}